[zshrc]
filename = ".zshrc"
from = "config/zshrc"
to = "test/.zshrc"
link_type = "soft"
owner = "dustin"
group = "dustin"
destroy = false

[vimrc]
filename = ".vimrc"
from = "config/vimrc"
to = "test/.vimrc"
link_type = "soft"
owner = "dustin"
group = "dustin"
destroy = false
