[zshrc]
target = '$PWD/config/.zshrc'
link_name = '~/.zshrc'

[vimrc]
target = '$PWD/config/.vimrc'
link_name = '~/.vimrc'

[ideavimrc]
target = '$PWD/config/.ideavimrc'
link_name = '~/.ideavimrc'

[ssh-config]
target = '$PWD/config/.ssh/config'
link_name = '~/.ssh/config'

[id_rsa]
target = '$PWD/config/.ssh/id_rsa'
link_name = '~/.ssh/id_rsa'

[id_rsa_pub]
target = '$PWD/config/.ssh/id_rsa.pub'
link_name = '~/.ssh/id_rsa.pub'

[bira2]
target = '$PWD/config/.oh-my-zsh/themes/bira2.zsh-theme'
link_name = '~/.oh-my-zsh/themes/bira2.zsh-theme'

[asdfrc]
target = '$PWD/config/.asdfrc'
link_name = '~/.asdfrc'

[gitconfig]
target = '$PWD/config/.gitconfig'
link_name = '~/.gitconfig'

[envvar]
target = '$PWD/config/.config/environment.d/envvar.sh'
link_name = '~/.config/environment.d/envvar.sh'

[sshagent]
target = '$PWD/config/.config/systemd/user/ssh-agent.service'
link_name = '~/.config/systemd/user/ssh-agent.service'

[mozwayland]
target = '$PWD/config/.config/plasma-workspace/env/mozwayland.sh'
link_name = '~/.config/plasma-workspace/env/mozwayland.sh'

[thefuck]
target = '$PWD/config/.config/thefuck/settings.py'
link_name = '~/.config/thefuck/settings.py'